KitchensWithZest/Models/ViewModels/GalleryView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace KitchensWithZest.Models.ViewModels
{
    public class GalleryView
    {
        [Required]
        [DisplayName("Gallery Title")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName("Main Photo")]
        public string MainPhotoPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase MainPhotoFile { get; set; }

        [DisplayName("Photo")]
        public string PhotoPath { get; set; }
        [NotMapped]
        public IEnumerable<HttpPostedFileBase> PhotoFile { get; set; }

        public Gallery galleries { get; set; }
        public Photo photos { get; set; }
    }
}

KitchensWithZest/Controllers/GalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models.ViewModels;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class GalleriesController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: Galleries
        public ActionResult Index()
        {
            List<Gallery> galleries = db.Galleries.OrderByDescending(x => x.GalleryId).ToList();
            return View(galleries);
        }

        // GET: Galleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.GalleryId == id)
                .OrderByDescending(a=>a.PhotoId).ToList();
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // GET: Galleries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Galleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GalleryView galleryView, IEnumerable<HttpPostedFileBase> PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //Upload gallery main photo to ~/Images/Galleries
                string filename = Path.GetFileNameWithoutExtension(galleryView.MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(galleryView.MainPhotoFile.FileName);
                galleryView.MainPhotoPath = "~/Images/Galleries/" + filename;
                filename = Path.Combine(Server.MapPath("~/Images/Galleries/"), filename);
                galleryView.MainPhotoFile.SaveAs(filename);

                //Pass the gallery inf from ProductView model to Gallery model
                Gallery gallery = new Gallery();
                gallery.Title = galleryView.Title;
                gallery.Description = galleryView.Description;
                gallery.MainPhotoPath = galleryView.MainPhotoPath;

                //Save the gallery inf into database table Gallery
                db.Galleries.Add(gallery);
                db.SaveChanges();

                //Upload multiple gallery photos to ~/Images/Galleries
                foreach (var file in galleryView.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename2 = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    galleryView.PhotoPath = "~/Images/Photos/" + filename2;
                    filename2 = Path.Combine(Server.MapPath("~/Images/Photos/"), filename2);
                    file.SaveAs(filename2);

                    //Pass the photo inf from ProductView model to Gallery model
                    Photo photo = new Photo();
                    photo.GalleryId = gallery.GalleryId;
                    photo.PhotoPath = galleryView.PhotoPath;

                    //Save the photo inf into database table Gallery
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View(galleryView);
        }

        // GET: Galleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int GalleryId, Gallery gallery, HttpPostedFileBase MainPhotoFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(MainPhotoFile.FileName);
                gallery.MainPhotoPath = "~/Images/Galleries/" + filename;
                MainPhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Galleries/"), filename));

                db.Entry(gallery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gallery);
        }

        // GET: Galleries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            db.Galleries.Remove(gallery);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Controllers/GalleryPhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class GalleryPhotosController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: GalleryPhotos/Create
        public ActionResult Create(int GalleryId, string Title)
        {
            ViewBag.GalleryId = GalleryId;
            ViewBag.GalleryTitle = Title;
            Photo photo = new Photo()
            {
                GalleryId = GalleryId
            };
            return View(photo);
        }

        // POST: GalleryPhotos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Photo photo, IEnumerable<HttpPostedFileBase> PhotoFile, int GalleryId)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in photo.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    photo.PhotoPath = "~/Images/Photos/" + filename;
                    filename = Path.Combine(Server.MapPath("~/Images/Photos/"), filename);
                    file.SaveAs(filename);

                    //Save the photo inf into database table Photo
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Details", "Galleries", new { id = photo.GalleryId });
            }

            return View(photo);
        }

        // GET: GalleryPhotos/Edit/5
        public ActionResult Edit(int? id, int GalleryId, string GalleryTitle)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.GalleryId = GalleryId;
            return View(photo);
        }

        // POST: GalleryPhotos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, int GalleryId, Photo photo, HttpPostedFileBase PhotoFile)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(PhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(PhotoFile.FileName);
                photo.PhotoPath = "~/Images/Photos/" + filename;
                PhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Photos/"), filename));

                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Galleries", new { id = photo.GalleryId });
            }
            ViewBag.GalleryId = GalleryId;
            return View(photo);
        }

        // GET: GalleryPhotos/Delete/5
        public ActionResult Delete(int? id, int GalleryId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: GalleryPhotos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int GalleryId)
        {
            Photo photo = db.Photos.Find(id);
            var GalId = photo.GalleryId;
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Details", "Galleries", new { id = GalId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Views/Galleries/Create.cshtml
@model KitchensWithZest.Models.ViewModels.GalleryView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Galleries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Add Gallery</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MainPhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="MainPhotoFile" required />
            @Html.ValidationMessageFor(model => model.MainPhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="PhotoFile" multiple />
            @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Galleries/Delete.cshtml
@model KitchensWithZest.Models.Gallery

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)"/>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KitchensWithZest/Views/Galleries/Details.cshtml
@model KitchensWithZest.Models.Gallery

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gallery</h4>
    <hr />
    <p>
        @Html.ActionLink("Back to List", "Index")  |
        @Html.ActionLink("Edit", "Edit", new { id = Model.GalleryId })
    </p>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)" />
        </dd>
    </dl>

    <hr />

    <dl class="dl-horizontal">
        <dt>
            Gallery Images
        </dt>

        <dd>
            @Html.ActionLink("Add Gallery photo", "Create", "GalleryPhotos", new { GalleryId = Model.GalleryId, Title = Model.Title@*, Description = Model.Description, MainPhotoPath = Model.MainPhotoPath*@}, null)
        </dd>

        <dd>
            @foreach (KitchensWithZest.Models.Photo item in ViewBag.Photos)
            {
                <p>
                    <img src="@Url.Content(item.PhotoPath)" width="50" />
                    @Html.ActionLink("Replace", "Edit", "GalleryPhotos", new { id = item.PhotoId, GalleryId = Model.GalleryId }, null) |
                    @Html.ActionLink("Delete", "Delete", "GalleryPhotos", new { id = item.PhotoId, GalleryId = Model.GalleryId }, null)

                </p>
            }
        </dd>
    </dl>
</div>

KitchensWithZest/Views/Galleries/Edit.cshtml
@model KitchensWithZest.Models.Gallery

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Galleries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GalleryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainPhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.MainPhotoPath)" width="300"/>
                <br />
                <input type="file" name="MainPhotoFile" required/>
                @Html.ValidationMessageFor(model => model.MainPhotoPath, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Galleries/Index.cshtml
@model IEnumerable<KitchensWithZest.Models.Gallery>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.PhotoPath)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="@Url.Content(item.MainPhotoPath)" width="50" />
            </td>
            @*<td>
                    @foreach (var photo in Model)
                    {
                        <img src="@Url.Content(item.photos.PhotoPath)" width="50" />
                    }

                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.GalleryId }) |
                @Html.ActionLink("Details", "Details", new { id = item.GalleryId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.GalleryId })
            </td>
        </tr>
    }

</table>