KitchensWithZest/Models/ViewModels/GalleryView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace KitchensWithZest.Models.ViewModels
{
    public class GalleryView
    {
        [Required]
        [DisplayName("Gallery Title")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName("Main Photo")]
        public string MainPhotoPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase MainPhotoFile { get; set; }

        [DisplayName("Photo")]
        public string PhotoPath { get; set; }
        [NotMapped]
        public IEnumerable<HttpPostedFileBase> PhotoFile { get; set; }

        public Gallery galleries { get; set; }
        public Photo photos { get; set; }
    }
}

KitchensWithZest/Models/ViewModels/ProductView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using KitchensWithZest.Models;

namespace KitchensWithZest.Models.ViewModels
{
    public class ProductView
    {
        [Required]
        [DisplayName("Product Title")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName("Main Photo")]
        public string MainPhotoPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase MainPhotoFile { get; set; }

        [DisplayName("Photo")]
        public string PhotoPath { get; set; }
        [NotMapped]
        public IEnumerable<HttpPostedFileBase> PhotoFile { get; set; }

        public List<Product> products { get; set; }
        public List<Photo> photos { get; set; }
    }
}

KitchensWithZest/Controllers/GalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models.ViewModels;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class GalleriesController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: Galleries
        public ActionResult Index()
        {
            List<Gallery> galleries = db.Galleries.OrderByDescending(x => x.GalleryId).ToList();
            return View(galleries);
        }

        // GET: Galleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.GalleryId == id)
                .OrderByDescending(a=>a.PhotoId).ToList();
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // GET: Galleries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Galleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GalleryView galleryView, IEnumerable<HttpPostedFileBase> PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //Upload gallery main photo to ~/Images/Galleries
                string filename = Path.GetFileNameWithoutExtension(galleryView.MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(galleryView.MainPhotoFile.FileName);
                galleryView.MainPhotoPath = "~/Images/Galleries/" + filename;
                filename = Path.Combine(Server.MapPath("~/Images/Galleries/"), filename);
                galleryView.MainPhotoFile.SaveAs(filename);

                //Pass the gallery inf from ProductView model to Gallery model
                Gallery gallery = new Gallery();
                gallery.Title = galleryView.Title;
                gallery.Description = galleryView.Description;
                gallery.MainPhotoPath = galleryView.MainPhotoPath;

                //Save the gallery inf into database table Gallery
                db.Galleries.Add(gallery);
                db.SaveChanges();

                //Upload multiple gallery photos to ~/Images/Galleries
                foreach (var file in galleryView.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename2 = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    galleryView.PhotoPath = "~/Images/Photos/" + filename2;
                    filename2 = Path.Combine(Server.MapPath("~/Images/Photos/"), filename2);
                    file.SaveAs(filename2);

                    //Pass the photo inf from ProductView model to Gallery model
                    Photo photo = new Photo();
                    photo.GalleryId = gallery.GalleryId;
                    photo.PhotoPath = galleryView.PhotoPath;

                    //Save the photo inf into database table Gallery
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View(galleryView);
        }

        // GET: Galleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int GalleryId, Gallery gallery, HttpPostedFileBase MainPhotoFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(MainPhotoFile.FileName);
                gallery.MainPhotoPath = "~/Images/Galleries/" + filename;
                MainPhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Galleries/"), filename));

                db.Entry(gallery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gallery);
        }

        // GET: Galleries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Galleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            db.Galleries.Remove(gallery);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Controllers/MessageBoxesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class MessageBoxesController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: MessageBoxes
        public ActionResult Index()
        {
            return View(db.MessageBoxes.OrderByDescending(x=>x.MessageId).ToList());
        }

        // GET: MessageBoxes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MessageBox messageBox = db.MessageBoxes.Find(id);
            if (messageBox == null)
            {
                return HttpNotFound();
            }
            return View(messageBox);
        }



        // GET: MessageBoxes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MessageBox messageBox = db.MessageBoxes.Find(id);
            if (messageBox == null)
            {
                return HttpNotFound();
            }
            return View(messageBox);
        }

        // POST: MessageBoxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MessageBox messageBox = db.MessageBoxes.Find(id);
            db.MessageBoxes.Remove(messageBox);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models.ViewModels;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class ProductsController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: Products
        public ActionResult Index()
        {
            List<Product> products = db.Products.OrderByDescending(x => x.ProductId).ToList();
            return View(products);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.ProductId == id)
                .OrderByDescending(a => a.PhotoId).ToList();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductView productView, IEnumerable<HttpPostedFileBase> PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //Upload product main photo to ~/Images/Products
                string filename = Path.GetFileNameWithoutExtension(productView.MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff") + Path.GetExtension(productView.MainPhotoFile.FileName);
                productView.MainPhotoPath = "~/Images/Products/" + filename;
                filename = Path.Combine(Server.MapPath("~/Images/Products/"), filename);
                productView.MainPhotoFile.SaveAs(filename);

                //Pass the product inf from ProductView model to Product model
                Product product = new Product();
                product.Title = productView.Title;
                product.Description = productView.Description;
                product.MainPhotoPath = productView.MainPhotoPath;

                //Save the product inf into database table Product
                db.Products.Add(product);
                db.SaveChanges();

                //Upload multiple product gallery photos to ~/Images/Photos
                foreach (var file in productView.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename2 = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    productView.PhotoPath = "~/Images/Photos/" + filename2;
                    filename2 = Path.Combine(Server.MapPath("~/Images/Photos/"), filename2);
                    file.SaveAs(filename2);

                    //Pass the photo inf from ProductView model to Photo model
                    Photo photo = new Photo();
                    photo.ProductId = product.ProductId;
                    photo.PhotoPath = productView.PhotoPath;

                    //Save the photo inf into database table Photo
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
                //return RedirectToAction("Details", new { id = product.ProductId });
            }

            return View(productView);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.ProductId == id)
                .OrderByDescending(a => a.PhotoId).ToList();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ProductId, Product product, HttpPostedFileBase MainPhotoFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(MainPhotoFile.FileName);
                product.MainPhotoPath = "~/Images/Products/" + filename;
                //filename = Path.Combine(Server.MapPath("~/Images/Products/"), filename);
                MainPhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Products/"), filename));

                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KitchensWithZest/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2>Management</h2>

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Product", "Index", "Products")</li>
        <li>@Html.ActionLink("Gallery", "Index", "Galleries")</li>
        <li>@Html.ActionLink("Contact", "Index", "MessageBoxes")</li>
    </ul>
</div>

KitchensWithZest/Views/Home/Contact.cshtml
@model KitchensWithZest.Models.MessageBox

@{
    ViewBag.Title = "Create";
}

<h2>Send a message</h2>


@using (Html.BeginForm("Contact", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    var message = "@TempData["SuccessMsg"]";
    if (message) {
        alert(message);
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Home/Gallery.cshtml
@model IEnumerable<KitchensWithZest.Models.Gallery>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.PhotoPath)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="@Url.Content(item.MainPhotoPath)" width="50" />
            </td>
         
            <td>
                @Html.ActionLink("Details", "GalleryDetails", new { id = item.GalleryId }) 
            </td>
        </tr>
    }

</table>

KitchensWithZest/Views/Home/GalleryDetails.cshtml
@model KitchensWithZest.Models.Gallery

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)" />
        </dd>
        <dt>
            Gallery Images
        </dt>
        <dd>
            @foreach (KitchensWithZest.Models.Photo item in ViewBag.Photos)
            {
                <img src="@Url.Content(item.PhotoPath)" width="50" />
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

KitchensWithZest/Views/Home/GetStart.cshtml
@{
    ViewBag.Title = "GetStart";
}

<h2>GetStart</h2>

KitchensWithZest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

KitchensWithZest/Views/Home/Product.cshtml
@model IEnumerable<KitchensWithZest.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.ImagesPath)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="@Url.Content(item.MainPhotoPath)" width="50" />
            </td>
            @*<td>
                    <img src="@Url.Content(item.ImagesPath)" width="50"/>
                </td>*@
            <td>
                @Html.ActionLink("Details", "ProductDetails", new { id = item.ProductId }) 
            </td>
        </tr>
    }

</table>

KitchensWithZest/Views/Home/ProductDetails.cshtml
@model KitchensWithZest.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagesPath)
        </dt>

        <dd>
            @foreach (KitchensWithZest.Models.Photo item in ViewBag.Photos)
            {
                <img src="@Url.Content(item.PhotoPath)" width="50" />
            }

        </dd>

    </dl>
</div>