KitchensWithZest/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class PhotosController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: Photos
        public ActionResult Index()
        {
            var photos = db.Photos.Include(p => p.Gallery).Include(p => p.Product);
            return View(photos.OrderByDescending(p=>p.PhotoId).ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            ViewBag.Gallery = new SelectList(db.Galleries, "GalleryId", "Title");
            ViewBag.Product = new SelectList(db.Products, "ProductId", "Title");
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "PhotoId,ProductId,GalleryId,PhotoPath")]*/ Photo photo, IEnumerable<HttpPostedFileBase> PhotoFile)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in photo.PhotoFile)
                {
                    if (file.ContentLength > 0)
                    {
                        string filename = Path.GetFileNameWithoutExtension(file.FileName)
                            + DateTime.Now.ToString("yymmssfff")
                            + Path.GetExtension(file.FileName);
                        photo.PhotoPath = "~/Images/Photos/" + filename;
                        filename = Path.Combine(Server.MapPath("~/Images/Photos/"), filename);
                        file.SaveAs(filename);
                            
                        db.Photos.Add(photo);
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.GalleryId = new SelectList(db.Galleries, "GalleryId", "Title", photo.GalleryId);
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Title", photo.ProductId);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.GalleryId = new SelectList(db.Galleries, "GalleryId", "Title", photo.GalleryId);
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Title", photo.ProductId);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int PhotoId, Photo photo, HttpPostedFileBase PhotoFiles)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(PhotoFiles.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(PhotoFiles.FileName);
                photo.PhotoPath = "~/Images/Photos/" + filename;
                PhotoFiles.SaveAs(Path.Combine(Server.MapPath("~/Images/Photos/"), filename));

                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GalleryId = new SelectList(db.Galleries, "GalleryId", "Title", photo.GalleryId);
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Title", photo.ProductId);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Views/Photos/Create.cshtml
@model KitchensWithZest.Models.Photo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Photos",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Photo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="PhotoFile" multiple />
            @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Product, "Product", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Product", null, "Select product (Option)", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gallery, "Gallery", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Gallery", null, "Select gallery (Option)", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Gallery, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Photos/Delete.cshtml
@model KitchensWithZest.Models.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gallery.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gallery.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KitchensWithZest/Views/Photos/Details.cshtml
@model KitchensWithZest.Models.Photo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gallery.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gallery.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PhotoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KitchensWithZest/Views/Photos/Edit.cshtml
@model KitchensWithZest.Models.Photo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Photo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PhotoId)

    <div class="form-group">
        @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PhotoFiles, new {type="file", htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductId", null, "Select product (Option)", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GalleryId, "GalleryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GalleryId", null, "Select gallery (Option)", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GalleryId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Photos/Index.cshtml
@model IEnumerable<KitchensWithZest.Models.Photo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gallery.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="@Url.Content(item.PhotoPath)" width="50"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gallery.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PhotoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PhotoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PhotoId })
        </td>
    </tr>
}

</table>