KitchensWithZest/Models/ViewModels/ProductView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using KitchensWithZest.Models;

namespace KitchensWithZest.Models.ViewModels
{
    public class ProductView
    {
        [Required]
        [DisplayName("Product Title")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName("Main Photo")]
        public string MainPhotoPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase MainPhotoFile { get; set; }

        [DisplayName("Photo")]
        public string PhotoPath { get; set; }
        [NotMapped]
        public IEnumerable<HttpPostedFileBase> PhotoFile { get; set; }

        public List<Product> products { get; set; }
        public List<Photo> photos { get; set; }
    }
}

KitchensWithZest/Controllers/ProductPhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class ProductPhotosController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: ProductPhotos/Create
        public ActionResult Create(int ProductId, string Title)
        {
            ViewBag.ProductId = ProductId;
            ViewBag.ProductTitle = Title;
            Photo photo = new Photo()
            {
                ProductId = ProductId
            };
            return View(photo);
        }

        // POST: ProductPhotos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Photo photo, IEnumerable<HttpPostedFileBase> PhotoFile, int ProductId)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in photo.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    photo.PhotoPath = "~/Images/Photos/" + filename;
                    filename = Path.Combine(Server.MapPath("~/Images/Photos/"), filename);
                    file.SaveAs(filename);

                    //Save the photo inf into database table Photo
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Details", "Products", new { id = photo.ProductId});
            }

            return View(photo);
        }

        // GET: ProductPhotos/Edit/5
        public ActionResult Edit(int? id, int ProductId, string ProductTitle)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = ProductId;
            return View(photo);
        }

        // POST: ProductPhotos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, int ProductId, Photo photo, HttpPostedFileBase PhotoFile)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(PhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(PhotoFile.FileName);
                photo.PhotoPath = "~/Images/Photos/" + filename;
                PhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Photos/"), filename));

                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Products", new { id = photo.ProductId });
            }
            ViewBag.ProductId = ProductId;
            return View(photo);
        }

        // GET: ProductPhotos/Delete/5
        public ActionResult Delete(int? id, int ProductId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: ProductPhotos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int ProductId)
        {
            Photo photo = db.Photos.Find(id);
            var ProId = photo.ProductId;
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Details", "Products", new { id = ProId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitchensWithZest.Models.ViewModels;
using KitchensWithZest.Models;

namespace KitchensWithZest.Controllers
{
    public class ProductsController : Controller
    {
        private KitchensWithZestEntities db = new KitchensWithZestEntities();

        // GET: Products
        public ActionResult Index()
        {
            List<Product> products = db.Products.OrderByDescending(x => x.ProductId).ToList();
            return View(products);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.ProductId == id)
                .OrderByDescending(a => a.PhotoId).ToList();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductView productView, IEnumerable<HttpPostedFileBase> PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //Upload product main photo to ~/Images/Products
                string filename = Path.GetFileNameWithoutExtension(productView.MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff") + Path.GetExtension(productView.MainPhotoFile.FileName);
                productView.MainPhotoPath = "~/Images/Products/" + filename;
                filename = Path.Combine(Server.MapPath("~/Images/Products/"), filename);
                productView.MainPhotoFile.SaveAs(filename);

                //Pass the product inf from ProductView model to Product model
                Product product = new Product();
                product.Title = productView.Title;
                product.Description = productView.Description;
                product.MainPhotoPath = productView.MainPhotoPath;

                //Save the product inf into database table Product
                db.Products.Add(product);
                db.SaveChanges();

                //Upload multiple product gallery photos to ~/Images/Photos
                foreach (var file in productView.PhotoFile)
                {
                    if (file == null)
                    {
                        return RedirectToAction("Index");
                    }
                    string filename2 = Path.GetFileNameWithoutExtension(file.FileName)
                        + DateTime.Now.ToString("yymmssfff")
                        + Path.GetExtension(file.FileName);
                    productView.PhotoPath = "~/Images/Photos/" + filename2;
                    filename2 = Path.Combine(Server.MapPath("~/Images/Photos/"), filename2);
                    file.SaveAs(filename2);

                    //Pass the photo inf from ProductView model to Photo model
                    Photo photo = new Photo();
                    photo.ProductId = product.ProductId;
                    photo.PhotoPath = productView.PhotoPath;

                    //Save the photo inf into database table Photo
                    db.Photos.Add(photo);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
                //return RedirectToAction("Details", new { id = product.ProductId });
            }

            return View(productView);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Photos = db.Photos.AsNoTracking()
                .Where(a => a.ProductId == id)
                .OrderByDescending(a => a.PhotoId).ToList();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ProductId, Product product, HttpPostedFileBase MainPhotoFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileNameWithoutExtension(MainPhotoFile.FileName)
                    + DateTime.Now.ToString("yymmssfff")
                    + Path.GetExtension(MainPhotoFile.FileName);
                product.MainPhotoPath = "~/Images/Products/" + filename;
                //filename = Path.Combine(Server.MapPath("~/Images/Products/"), filename);
                MainPhotoFile.SaveAs(Path.Combine(Server.MapPath("~/Images/Products/"), filename));

                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitchensWithZest/Views/Products/Create.cshtml
@model KitchensWithZest.Models.ViewModels.ProductView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainPhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="MainPhotoFile" required />
                @Html.ValidationMessageFor(model => model.MainPhotoPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="PhotoFile" multiple />
                @Html.ValidationMessageFor(model => model.PhotoPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Products/Delete.cshtml
@model KitchensWithZest.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)" width="100"/>
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ProGallery)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProGallery)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KitchensWithZest/Views/Products/Details.cshtml
@model KitchensWithZest.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <p>
        @Html.ActionLink("Back to List", "Index")  |
        @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId })
    </p>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.MainPhotoPath)" width="300"/>
        </dd>
    </dl>

    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagesPath)
        </dt>

        <dd>
            @Html.ActionLink("Add Product photo", "Create", "ProductPhotos", new { ProductId = Model.ProductId, Title = Model.Title@*, Description = Model.Description, MainPhotoPath = Model.MainPhotoPath*@}, null)
        </dd>
        @foreach (KitchensWithZest.Models.Photo item in ViewBag.Photos)
        {
            <dd>
                <img src="@Url.Content(item.PhotoPath)" width="50" />
                @Html.ActionLink("Replace", "Edit", "ProductPhotos", new { id = item.PhotoId, ProductId = Model.ProductId },null) |
                @Html.ActionLink("Delete", "Delete", "ProductPhotos", new { id = item.PhotoId, ProductId = Model.ProductId },null)
            </dd>
        }

    </dl>
</div>

KitchensWithZest/Views/Products/Edit.cshtml
@model KitchensWithZest.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Products",FormMethod.Post,new { enctype= "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainPhotoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.MainPhotoPath)" width="300"/>
                <br />
                <input type="file" name="MainPhotoFile" required/>
                @Html.ValidationMessageFor(model => model.MainPhotoPath, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ProGallery, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProGallery, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProGallery, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KitchensWithZest/Views/Products/Index.cshtml
@model IEnumerable<KitchensWithZest.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Products")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainPhotoPath)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ImagesPath)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            <img src="@Url.Content(item.MainPhotoPath)" width="50"/>
        </td>
        @*<td>
            <img src="@Url.Content(item.ImagesPath)" width="50"/>
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
        </td>
    </tr>
}

</table>